name: Package Unreal Engine Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    name: Package Unreal Engine Game
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Project
        env: 
          UE_PATH: 'D:\Epic Games\UE_5.3' # Path to your Unreal Engine installation
          PROJECT_PATH: 'D:\Game Development\Unreal Projects\CICDGO\CICDGO.uproject' # Path to your Unreal project file
          OUTPUT_PATH: 'D:\Game Development' # Path to where you want to store the packaged game
        run: |
        
          # Try to run empty UAT to check for correct path
          & $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"

      - name: Run Packaging Script
        run: |
          # Path to your Unreal Engine installation
          UE_PATH="D:\Epic Games\UE_5.3"

          # Path to your Unreal project file
          PROJECT_PATH="D:\Game Development\Unreal Projects\CICDGO\CICDGO.uproject"

          # Path to where you want to store the packaged game
          OUTPUT_PATH="D:\Game Development"

          # Try to run empty UAT to check for correct path
          "$UE_PATH\Engine\Build\BatchFiles\RunUAT.bat"

          # Run the packaging command
          "$UE_PATH\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="$PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$OUTPUT_PATH"
